#@data/values
---
git_uri: git@github.com:GaloyMoney/lana-bank.git
git_branch: main
github_private_key: ((github.private_key))
github_token: ((github.api_token))
github_app_id: ((github.github_app_id))
github_app_private_key: ((github.github_app_private_key))

git_charts_uri: git@github.com:GaloyMoney/galoy-private-charts.git
git_charts_branch: main
git_charts_bot_branch: bot-bump-lana-bank-image
docker_registry: us.gcr.io/galoyorg
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))

docker_host_ip: ((staging-ssh.docker_host_ip))
git_version_branch: version
gh_org: GaloyMoney
gh_repository: lana-bank
